---
- name: Join cluster as Worker
  command: >
    kubeadm join
    --token {{ admission_token }}
    {{ master_ip }}:6443
    --discovery-token-unsafe-skip-ca-verification
  args:
    creates: /etc/kubernetes/kubelet.conf
